// Offline fallback mirroring docs/seed.sql — used only when Supabase is
// unreachable. The live menu (with translations) comes from lib/menu.ts.
type MenuCategory = { id: string; name: string; emoji: string };
type MenuItem = {
  id: string;
  categoryId: string;
  name: string;
  description: string;
  priceInr: number;
  isVeg: boolean;
  spiceLevel: 0 | 1 | 2 | 3;
  allergens: string[];
  tags: string[];
};

export const RESTAURANT = {
  name: "Spice Garden",
  slug: "demo-spice-garden",
  upiVpa: "demo@upi",
  tagline: "Authentic Indian kitchen",
  // admin setting: "post" = order first, pay at the end; "pre" = pay to place the order
  paymentTiming: "post" as "pre" | "post",
};

export const CATEGORIES: MenuCategory[] = [
  { id: "starters", name: "Starters", emoji: "🍢" },
  { id: "mains", name: "Main Course", emoji: "🍛" },
  { id: "breads", name: "Breads", emoji: "🫓" },
  { id: "biryani", name: "Biryani & Rice", emoji: "🍚" },
  { id: "desserts", name: "Desserts", emoji: "🍮" },
  { id: "drinks", name: "Drinks", emoji: "🥤" },
];

export const MENU: MenuItem[] = [
  {
    id: "paneer-tikka",
    categoryId: "starters",
    name: "Paneer Tikka",
    description:
      "Char-grilled cottage cheese cubes marinated in yogurt, ginger-garlic and kasuri methi, served with mint chutney.",
    priceInr: 280,
    isVeg: true,
    spiceLevel: 2,
    allergens: ["dairy"],
    tags: ["bestseller"],
  },
  {
    id: "veg-manchurian",
    categoryId: "starters",
    name: "Veg Manchurian",
    description: "Crispy vegetable dumplings tossed in a garlicky Indo-Chinese sauce.",
    priceInr: 240,
    isVeg: true,
    spiceLevel: 2,
    allergens: ["soy", "gluten"],
    tags: [],
  },
  {
    id: "chicken-65",
    categoryId: "starters",
    name: "Chicken 65",
    description:
      "Deep-fried chicken bites with curry leaves, dried red chilli and a hint of ginger.",
    priceInr: 320,
    isVeg: false,
    spiceLevel: 3,
    allergens: [],
    tags: ["bestseller", "spicy"],
  },
  {
    id: "tandoori-mushroom",
    categoryId: "starters",
    name: "Tandoori Mushroom",
    description: "Button mushrooms in smoky tandoori masala, finished with chaat masala.",
    priceInr: 260,
    isVeg: true,
    spiceLevel: 1,
    allergens: ["dairy"],
    tags: [],
  },
  {
    id: "paneer-butter-masala",
    categoryId: "mains",
    name: "Paneer Butter Masala",
    description:
      "Cottage cheese simmered in a silky tomato-cashew gravy with butter and cream. Mildly sweet.",
    priceInr: 320,
    isVeg: true,
    spiceLevel: 1,
    allergens: ["dairy", "nuts"],
    tags: ["bestseller"],
  },
  {
    id: "dal-makhani",
    categoryId: "mains",
    name: "Dal Makhani",
    description: "Black lentils slow-cooked overnight with butter and cream.",
    priceInr: 280,
    isVeg: true,
    spiceLevel: 0,
    allergens: ["dairy"],
    tags: ["chef-special"],
  },
  {
    id: "butter-chicken",
    categoryId: "mains",
    name: "Butter Chicken",
    description: "Tandoor-smoked chicken in a rich tomato-butter gravy. Our signature.",
    priceInr: 380,
    isVeg: false,
    spiceLevel: 1,
    allergens: ["dairy", "nuts"],
    tags: ["bestseller"],
  },
  {
    id: "andhra-chicken-curry",
    categoryId: "mains",
    name: "Andhra Chicken Curry",
    description: "Fiery country-style chicken curry with guntur chillies. Properly hot.",
    priceInr: 360,
    isVeg: false,
    spiceLevel: 3,
    allergens: [],
    tags: ["spicy"],
  },
  {
    id: "palak-paneer",
    categoryId: "mains",
    name: "Palak Paneer",
    description: "Fresh spinach purée with soft paneer cubes and a touch of garlic.",
    priceInr: 300,
    isVeg: true,
    spiceLevel: 1,
    allergens: ["dairy"],
    tags: [],
  },
  {
    id: "butter-naan",
    categoryId: "breads",
    name: "Butter Naan",
    description: "Tandoor-baked, brushed with butter.",
    priceInr: 60,
    isVeg: true,
    spiceLevel: 0,
    allergens: ["gluten", "dairy"],
    tags: [],
  },
  {
    id: "garlic-naan",
    categoryId: "breads",
    name: "Garlic Naan",
    description: "Naan topped with garlic and coriander.",
    priceInr: 75,
    isVeg: true,
    spiceLevel: 0,
    allergens: ["gluten", "dairy"],
    tags: ["bestseller"],
  },
  {
    id: "tandoori-roti",
    categoryId: "breads",
    name: "Tandoori Roti",
    description: "Whole-wheat, baked in the tandoor.",
    priceInr: 40,
    isVeg: true,
    spiceLevel: 0,
    allergens: ["gluten"],
    tags: [],
  },
  {
    id: "hyderabadi-chicken-biryani",
    categoryId: "biryani",
    name: "Hyderabadi Chicken Biryani",
    description:
      "Dum-cooked basmati layered with marinated chicken, saffron and fried onions. Served with raita and salan.",
    priceInr: 380,
    isVeg: false,
    spiceLevel: 2,
    allergens: ["dairy"],
    tags: ["bestseller", "chef-special"],
  },
  {
    id: "veg-dum-biryani",
    categoryId: "biryani",
    name: "Veg Dum Biryani",
    description: "Seasonal vegetables and basmati dum-cooked with mint and saffron.",
    priceInr: 300,
    isVeg: true,
    spiceLevel: 2,
    allergens: ["dairy"],
    tags: [],
  },
  {
    id: "jeera-rice",
    categoryId: "biryani",
    name: "Jeera Rice",
    description: "Basmati tempered with cumin and ghee.",
    priceInr: 180,
    isVeg: true,
    spiceLevel: 0,
    allergens: ["dairy"],
    tags: [],
  },
  {
    id: "gulab-jamun",
    categoryId: "desserts",
    name: "Gulab Jamun (2 pcs)",
    description: "Soft khoya dumplings soaked in cardamom-rose syrup. Served warm.",
    priceInr: 120,
    isVeg: true,
    spiceLevel: 0,
    allergens: ["dairy", "gluten"],
    tags: ["bestseller"],
  },
  {
    id: "rasmalai",
    categoryId: "desserts",
    name: "Rasmalai (2 pcs)",
    description: "Chenna discs in chilled saffron-pistachio milk.",
    priceInr: 140,
    isVeg: true,
    spiceLevel: 0,
    allergens: ["dairy", "nuts"],
    tags: [],
  },
  {
    id: "sweet-lassi",
    categoryId: "drinks",
    name: "Sweet Lassi",
    description: "Thick churned yogurt, lightly sweetened.",
    priceInr: 90,
    isVeg: true,
    spiceLevel: 0,
    allergens: ["dairy"],
    tags: [],
  },
  {
    id: "masala-chaas",
    categoryId: "drinks",
    name: "Masala Chaas",
    description: "Spiced buttermilk with roasted cumin and coriander.",
    priceInr: 70,
    isVeg: true,
    spiceLevel: 1,
    allergens: ["dairy"],
    tags: [],
  },
  {
    id: "fresh-lime-soda",
    categoryId: "drinks",
    name: "Fresh Lime Soda",
    description: "Sweet, salted, or mixed.",
    priceInr: 80,
    isVeg: true,
    spiceLevel: 0,
    allergens: [],
    tags: [],
  },
];

