export const queryKeys = {
  me: ["admin", "me"] as const,
  kitchen: ["kitchen"] as const,
  floor: ["floor"] as const,
  bill: (sessionId: string) => ["bill", sessionId] as const,
  waiter: ["waiter"] as const,
  tips: ["waiter", "tips"] as const,
  counter: ["counter"] as const,
  adminMenu: ["admin", "menu"] as const,
  adminStaff: ["admin", "staff"] as const,
  adminTables: ["admin", "tables"] as const,
  adminOrders: (range: string) => ["admin", "orders", range] as const,
  menu: (tableCode: string) => ["menu", tableCode] as const,
  session: (tableCode: string) => ["session", tableCode] as const,
  orderRounds: (sessionId: string) => ["order", "rounds", sessionId] as const,
  customerBill: (sessionId: string, tip: number) => ["bill", "customer", sessionId, tip] as const,
};
